name: Larastan

on:
  push:
    branches: [ main ]
  pull_request:    

jobs:
  larastan-test:
    runs-on: ubuntu-latest
        
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      
      - name: Install Composer dependencies
        run: composer install -q --prefer-dist --no-progress
      
      - name: Run Larastan
        run: php vendor/bin/phpstan analyse